# Generated by Django 5.2.7 on 2025-10-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Інше', 'Other'), ('Дебют', 'Debut'), ('Мітельшпіль', 'Middle Game'), ('Ендшпіль', 'End Game'), ('Історія', 'History'), ('Шахові задачки', 'Etude')], default='Інше'),
        ),
    ]
