# Generated by Django 5.2.7 on 2025-11-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='elements_num',
            field=models.IntegerField(default=1),
        ),
    ]
