# Generated by Django 5.2.7 on 2025-11-13 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_newsletter', models.BooleanField(default=False)),
                ('on_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_on_whom', to=settings.AUTH_USER_MODEL)),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_who', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
