# Generated by Django 5.2.7 on 2025-12-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_dislike_article_alter_like_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
