# Generated by Django 5.2.7 on 2026-01-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Інше', 'Other'), ('Дебют', 'Debut'), ('Мітельшпіль', 'Middle Game'), ('Ендшпіль', 'End Game'), ('Історія шахів', 'History'), ('Шахові задачки', 'Etude')], default='Інше'),
        ),
    ]
